version: '3'
services:

  tds_psql:
     image: frodenas/postgresql:latest
     container_name: tds_psql
     ports:
        - 5432:5432
     volumes:
       - /opt/tds_psql:/var/lib/postgresql/data
     environment:
       POSTGRES_PASSWORD: 123456
       POSTGRES_USERNAME: tds
       POSTGRES_DBNAME: tds_test

  eureka-server:
    image: wisdomchain/eureka-server:latest
    container_name: eureka-server
    restart: always
    hostname: eureka-server
    ports:
      - 8761:8761
    environment:
      HOST_NAME: 'eureka-server'

  sync-service:
    image: wisdomchain/sync-service:latest
    container_name: sync-service
    restart: always
    ports:
      - 9092:9092
    environment:
      EUREKA_SERVICE_URL: 'http://eureka-server:8761'
      DATA_SOURCE_URL: 'jdbc:postgresql://tds_psql:5432/tds_test'
      DB_USERNAME: 'tds'
      DB_PASSWORD: '123456'
      NODE_URL: 'http://192.168.1.52:7010'

  tds-web:
    image: wisdomchain/tds-web:latest
    container_name: tds-web
    restart: always
    ports:
      - 8080:8080
    environment:
      EUREKA_SERVICE_URL: 'http://eureka-server:8761'
      DATA_SOURCE_URL: 'jdbc:postgresql://tds_psql:5432/tds_test'
      DB_USERNAME: 'tds'
      DB_PASSWORD: '123456'
      NODE_URL: 'http://192.168.1.52:7010'
