spring:
  datasource:
      url: ${DATA_SOURCE_URL:jdbc:postgresql://192.168.1.138:5432/tdos}
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:123456}
#      schema: classpath:db-migration.sql
#      initialization-mode: ${DB_INIT_MODE:always}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      connection:
        release_mode: 'after_statement'
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.jdbc.time_zone : UTC
    properties.javax.persistence.query.timeout: 20000
    properties.hibernate.jdbc.batch_size: 500
    properties.hibernate.jdbc.batch_versioned_data: true
    properties.hibernate.order_inserts: true
    properties.hibernate.order_updates: true


dandelion:
  peers: ${NODE_URL:http://192.168.1.188:7012}
