spring:
  datasource:
    url: ${DATA_SOURCE_URL:jdbc:h2:./h2/h2;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:123123liu}
    schema: classpath:db-migration.sql
    driverClassName: org.h2.Driver
    separator: ;

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: false
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      connection:
        release_mode: 'after_statement'
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.jdbc.time_zone : UTC
    properties.javax.persistence.query.timeout: 20000
    properties.hibernate.jdbc.batch_size: 500
    properties.hibernate.jdbc.batch_versioned_data: true
    properties.hibernate.order_inserts: true
    properties.hibernate.order_updates: true


dandelion:
  peers: ${NODE_URL:http://192.168.1.188:7010}
