spring:
  datasource:
      url: ${DATA_SOURCE_URL:jdbc:postgresql://8.210.39.91:5432/tds_test}
      username: ${DB_USERNAME:tds}
      password: ${DB_PASSWORD:123456}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      connection:
        release_mode: 'after_statement'
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.jdbc.time_zone : UTC
    properties.javax.persistence.query.timeout: 20000
    properties.hibernate.jdbc.batch_size: 500
    properties.hibernate.jdbc.batch_versioned_data: true
    properties.hibernate.order_inserts: true
    properties.hibernate.order_updates: true


dandelion:
  peers: ${NODE_URL:http://localhost:7010}