server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOST_NAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: eureka-server
